version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
    groups:
      snowfl-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
        exclude-patterns:
          - "pytest"
          - "coverage"
          - "build"
          - "twine"
          - "pytest-rerunfailures"
      snowfl-dev-minor-patch:
        patterns:
          - "pytest"
          - "coverage"
          - "build"
          - "twine"
          - "pytest-rerunfailures"
        update-types:
          - "minor"
          - "patch"
